---
title: "Assignment 1"
output: pdf_document
---

```{r,warning=FALSE,message=FALSE,eval=FALSE,echo=FALSE}
library(fjolst)
library(dplyr)
library(data.table)

stations <- 
  stodvar %>% 
  filter(synaflokkur == 30) 

samples <- 
  all.kv %>%
  filter(synis.id %in% stations$synis.id) %>%# &
  #           tegund %in% species.key$tegund) %>%
  group_by(synis.id,tegund) %>%
  left_join(stations) %>%
  #    left_join(species.key) %>%
  mutate(sex = c('M','F')[pmax(1,kyn)],
         maturity_stage = pmax(1,pmin(kynthroski,2))) %>%
  select(sample.id = synis.id, year=ar, month=man, day = dags, 
         station.id = stod, lat, lon, depth = dypi, sex, maturity_stage,
         age = aldur, length = lengd, ungutted.weight=oslaegt,
         gutted.weight=slaegt, liver.weight=lifur, gonad.weight=kynfaeri,
         species=tegund)

tmp <- samples %>%  group_by(species) %>% 
  summarise(n = length(sample.id),w=sum(!is.na(ungutted.weight)),a=sum(!is.na(age))) %>% 
  arrange(desc(n)) %>% slice(1:10) 

dir.create('species')
for(i in tmp$species){
  samples %>% 
  filter(species == i) %>% 
  write.csv2(sprintf('species/species-%s.csv',i))
}                            
  

```

# Introduction 
The dataset in this excercise was collected from the Icelandic groundfish survey, which has been conducted every year since 1984 and features between 530 and 600 haul stations. In the survey, up to 155 unique species have been identified and recorded although the main focus is in the top commercially exploited species such as cod, halibut and saithe. It is used as a basis for assessment for nearly all of the key exploited species and provides valuable information on state of the ecosystem. 

The survey occurs in March every year with sample hauls (stations) taken on more than 500 at fixed locations. For each station the catch is analysed, species identified and length recorded. Age, sex, weight and maturity is recorded for a subsample. 

Each student will be assigned a species which the student will use in this excercise.


# Read in and describe the data
In the folder ''species'' you will find files names according to the shortname in the table above. Read in your species into R and summarise the data (hint: use ''summary'' and ''str''). 

* What variables are in the dataset?
* How many obervations are in the data?
* Are there any missing values? 
    + If so, where and why?

## Compile statistics
* Find the total number of survey stations where the species have been observed
    + Calculate the number of stations by year where the species is found 
    + Illustrate the number of stations by year using a bar plot
    + Indicate, in another bar plot, spatial changes by assigning different fill color to stations north of 65° degrees latitude
    
* Number of individuals caught in the survey fluctuates from station to station. Illustrate this by:
    + creating a bar-plot of the number individuals caught at each station, by year (using facet_wrap)
    + indicate spatial changes by assigning different fill color to fish caught north of 65° degrees latitude

    
* Investigate the age length relationship:
    + Plot a scatterplot of age and length  
    + **Bonus**: Plot a boxplot of age and length
    + **Bonus**: Fit a Von Bertalanffy curve to the age length data 


* Investigate changes of over time:
    + Plot length distributions by year
    + Calculate mean length by year and produce a table
    +  **Bonus**: Calculate mean weight by age and year and plot


# Report 
Produce a short report of your findings with the R-code you used.  

